### ISSUE TITLE
A single version of 3rd party dependencies with tools.deps

### ISSUE THREAD

**Issue by markdingram** [juxt/edge#37]
Would be desirable for a number of reasons to guarantee a single version of each 3rd party lib across all modules, not the case for now:

![screenshot 2018-12-14 at 08 34 33](https://user-images.githubusercontent.com/249217/49992173-2dd82380-ff7b-11e8-8813-d7f06fb0443e.png)
etc..

In Lein this would be where [managed deps](https://github.com/technomancy/leiningen/blob/master/doc/MANAGED_DEPS.md) comes in.

Doesn't seem to be any great way to do this with current tools.deps, one (admittedly clunky) option would be a deps.edn in the root of edge with an alias of override deps for all the 3rd party libs. Set CLJ_CONFIG to the root of edge and make sure that alias is always specified.

Or a Make/Mach preprocessor?

**Comment by SevereOverfl0w** [comment]
I'm not keen on any solutions that require setting CLJ_CONFIG.
The primary reasoning being that it stops me from setting useful aliases in my personal development setup.
e.g. if I'm working on kick, I have `:user/kick` setup for my machine paths.

There has been some indication that tools.deps will expose the required data for this feature at some point.
However, this is not a major issue from the perspective of tools.deps.
This is because tools.deps doesn't resolve dependencies like maven does.
Maven uses the first version it finds, which could be very old, or very new.
tools.deps uses the _most recent_ version, which alleviates the common path of unintentionally using old versions of transitive dependencies.

**Comment by markdingram** [comment]
gone stale!
